### ISSUE TITLE
Stuck in task "Manage configuration templating"

### ISSUE THREAD

**Issue by pat-s** [infOpen/ansible-role-airflow#180]
Hi,

while trying to use this role (latest master with airflow 1.10.11) I get stuck in the following task:

```
TASK [infOpen.airflow : CONFIG | Manage configuration templating] **********************
task path: /Users/pjs/.ansible/roles/infOpen.airflow/tasks/manage_configuration.yml:24

[...]

fatal: [airflow-server]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"
}
```

Looks like a variable is not defined? Any idea which one?

**Comment by achaussier** [comment]
Hello,

I've planed an update of this role to apply latest role template (see #178 ).

This will fix this issue, due to Python3 usage (`iteritems` is Python2 syntax). If you want a quick manual fix, you can replace `iteritems` by `items` and this should be sufficient.

Have a nice day

**Comment by pat-s** [comment]
Thanks, worked.

I also had to set `airflow_drop_existing_connections_before_add: false`, otherwise I would error in 

https://github.com/infOpen/ansible-role-airflow/blob/23c6cf0f465fe34df6b0b12e60d344abbfdf4260/tasks/manage_connections.yml#L15-L22

**Comment by achaussier** [comment]
Thanks for this information.

New release will come in the next days with this fix
